image_height: 512
image_width: 512
num_classes: 80
classes:
  [
    "airplane",
    "apple",
    "backpack",
    "banana",
    "baseball bat",
    "baseball glove",
    "bear",
    "bed",
    "bench",
    "bicycle",
    "bird",
    "boat",
    "book",
    "bottle",
    "bowl",
    "broccoli",
    "bus",
    "cake",
    "car",
    "carrot",
    "cat",
    "cell phone",
    "chair",
    "clock",
    "couch",
    "cow",
    "cup",
    "dining table",
    "dog",
    "donut",
    "elephant",
    "fire hydrant",
    "fork",
    "frisbee",
    "giraffe",
    "hair drier",
    "handbag",
    "horse",
    "hot dog",
    "keyboard",
    "kite",
    "knife",
    "laptop",
    "microwave",
    "motorcycle",
    "mouse",
    "orange",
    "oven",
    "parking meter",
    "person",
    "pizza",
    "potted plant",
    "refrigerator",
    "remote",
    "sandwich",
    "scissors",
    "sheep",
    "sink",
    "skateboard",
    "skis",
    "snowboard",
    "spoon",
    "sports ball",
    "stop sign",
    "suitcase",
    "surfboard",
    "teddy bear",
    "tennis racket",
    "tie",
    "toaster",
    "toilet",
    "toothbrush",
    "traffic light",
    "train",
    "truck",
    "tv",
    "umbrella",
    "vase",
    "wine glass",
    "zebra",
  ]

clip_default_boxes: No
scales: [0.04, 0.1, 0.26, 0.42, 0.58, 0.74, 0.9, 1.06]
feature_shapes: [[64, 64], [32, 32], [16, 16], [8, 8], [6, 6], [4, 4], [1, 1]]
aspect_ratios:
  [
    [0.5, 1, 2],
    [0.333, 0.5, 1, 2, 3],
    [0.333, 0.5, 1, 2, 3],
    [0.333, 0.5, 1, 2, 3],
    [0.5, 1, 2],
    [0.5, 1, 2],
    [0.5, 1, 2],
  ]
loc_variance: [0.1, 0.1, 0.2, 0.2]

match_iou_threshold: 0.5
max_detections: 300

nms_iou_threshold: 0.5
score_threshold: 0.0001

loc_loss_weight: 1.0
cls_loss_weight: 1.0
negatives_ratio: 3
smooth_l1_delta: 1.0

backbone: resnet_50
freeze_bn: No

train_images: 117266
val_images: 4952

tfrecords_train: gs://tfrc-srihari-europe/coco_tfrecords/train*
tfrecords_val: gs://tfrc-srihari-europe/coco_tfrecords/val*

model_dir: gs://tfrc-srihari-europe/model_files/coco/resnet_50_512x512-16

batch_size: 16
lr_boundaries: [500, 10000, 90000, 180000]
lr_values: [0.00006, 0.001, 0.0005, 0.0001, 0.00005]
optimizer_momentum: 0.95
nestrov: Yes

l2_regularization: 0.0004
epochs: 1000
patience: 1000
cache_dataset_in_memory: Yes

resume_training: Yes
clear_previous_runs: Yes

use_mixed_precision: Yes

use_gpu: No
multi_gpu: No

use_tpu: Yes
tpu_name: tfrc-srihari-v3-1

scale_lr: Yes
scale_batch_size: Yes

augment_val_dataset: No
random_pad_to_square: Yes
random_brightness: No
random_contrast: Yes
random_saturation: Yes
random_flip_horizonal: No
random_patch: Yes

max_pad_ratio: 4
brightness_max_delta: 0.15
contrast_lower: 0.5
contrast_upper: 1.5
saturation_lower: 0.5
saturation_upper: 1.5
min_obj_covered: [0.25, 0.4, 0.6, 0.8, 1]
area_range: [0.12, 1]
aspect_ratio_range: [0.75, 1.333]
