image_height: 300
image_width: 300
num_classes: 2
classes: [circle, rectangle]

clip_default_boxes: No
scales: [0.1, 0.2, 0.37, 0.54, 0.71, 0.88, 1.05]
feature_shapes: [[38, 38], [19, 19], [10, 10], [5, 5], [3, 3], [1, 1]]
aspect_ratios:
  [
    [0.5, 1, 2],
    [0.333, 0.5, 1, 2, 3],
    [0.333, 0.5, 1, 2, 3],
    [0.333, 0.5, 1, 2, 3],
    [0.5, 1, 2],
    [0.5, 1, 2],
    [0.5, 1, 2],
  ]
loc_variance: [0.1, 0.1, 0.2, 0.2]

match_iou_threshold: 0.5
max_detections: 10

nms_iou_threshold: 0.5
score_threshold: 0.5

loc_loss_weight: 1.0
cls_loss_weight: 1.0
negatives_ratio: 3
smooth_l1_delta: 1.0

backbone: resnet_50_v2
freeze_bn: No

train_images: 10000
val_images: 2500

tfrecords_train: ssd/data/dataset_files/shapes_dataset/train*
tfrecords_val: ssd/data/dataset_files/shapes_dataset/val*

model_dir: model_files/shaped_dataset/resnet_50_512x512

batch_size: 16
lr_boundaries: [12500]
lr_values: [0.001, 0.0001]
optimizer_momentum: 0.95
nestrov: Yes

l2_regularization: 0.0004
epochs: 30
patience: 8
cache_dataset_in_memory: Yes

resume_training: No
clear_previous_runs: Yes

use_mixed_precision: No

use_gpu: Yes
multi_gpu: Yes

use_tpu: No
tpu_name: tfrc-srihari-v3-5

scale_lr: Yes
scale_batch_size: Yes

augment_val_dataset: No
random_pad_to_square: Yes
random_brightness: Yes
random_contrast: Yes
random_saturation: Yes
random_flip_horizonal: No
random_patch: Yes

max_pad_ratio: 4
brightness_max_delta: 0.15
contrast_lower: 0.5
contrast_upper: 1.5
saturation_lower: 0.5
saturation_upper: 1.5
min_obj_covered: [0.25, 0.4, 0.6, 0.8, 1]
area_range: [0.12, 1]
aspect_ratio_range: [0.75, 1.333]
